name: Build
on:
  workflow_dispatch:
  push:
    branches:
      - main
      - release-*
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build wheel (${{ matrix.compiler.name }})
    runs-on: ubuntu-24.04
    container:
      image: nvidia/cuda:12.8.1-cudnn-devel-ubuntu24.04
    strategy:
      matrix:
        compiler:
          - name: clang
            cc: gcc-13
            cxx: g++-13
            packages: gcc-13 g++-13
    env:
      CMAKE_GENERATOR: Ninja
      CMAKE_C_COMPILER: ${{ matrix.compiler.cc }}
      CMAKE_CXX_COMPILER: ${{ matrix.compiler.cxx }}
      CMAKE_C_COMPILER_LAUNCHER: ccache
      CMAKE_CXX_COMPILER_LAUNCHER: ccache
      CMAKE_CUDA_COMPILER_LAUNCHER: ccache
      CUDAARCHS: "89"
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install deps
        run: apt update && apt install -y git wget build-essential cmake ninja-build git python3-dev ${{ matrix.compiler.packages }} libopenmpi-dev

      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v7

      - name: Build wheel
        run: uv build --wheel

      - name: Upload wheel
        uses: actions/upload-artifact@v4
        with:
          name: wheel-${{ matrix.compiler.name }}
          path: dist/*.whl
